[package]
name = "simhash"
version = "0.4.1"
authors = []
edition = "2021"

[lib]
name = "simhash"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.35.0"

[dependencies.simhash]
git = "https://github.com/holsee/simhash-rs.git"
